# Generated by Django 3.2.9 on 2021-11-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurants',
            new_name='Restaurant',
        ),
    ]
