# Generated by Django 3.2.9 on 2022-01-31 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_system', '0002_auto_20220131_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'managed': False},
        ),
    ]
