# Generated by Django 3.2.9 on 2022-01-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_system', '0003_alter_restaurant_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurant',
        ),
    ]
